Object.assign(window.QA=window.QA||{},{
"M1":[["Prime number kise kehte hain?","Jo sirf 1 aur khud se divisible ho."],["1 se 100 tak kitne prime?","25."],["Divisibility by 9 ka rule?","Digits ka sum 9 se divisible."],["HCF × LCM = ?","Dono numbers ka product (sirf do numbers ke liye)."],["Unit digit me 2 ka chakra?","2, 4, 8, 6 (4 ka chakra)."],["Even prime kaun sa?","2."],["0! = ?","1."],["√2 ka lagbhag value?","1.414."]],
"M2":[["1/8 = ? %","12.5%."],["Profit % kis par nikalte hain?","Cost Price (CP) par."],["Discount % kis par?","Marked Price (MP) par."],["Net % jab a% badhe phir a% ghate?","−a²/100 %."],["1/6 = ? %","16.67%."],["SP = ?","CP × (100 + P%)/100."],["25% ka fraction?","1/4."],["Population growth ka formula?","P(1 + r/100)ⁿ."]],
"M3":[["Mean proportional (a, b)?","√(ab)."],["Average ka formula?","Sum ÷ Count."],["a:b = c:d me kya barabar?","ad = bc."],["Partnership me profit kis ratio me?","Paisa × Samay."],["Alligation kis kaam aata hai?","Do cheezon ko mila kar mean price nikalne me."],["n natural numbers ka average?","(n+1)/2."],["Third proportional (a, b)?","b²/a."],["3 saal baad umar?","Abhi ki umar + 3."]],
"M4":[["SI ka formula?","PRT/100."],["CI ka formula?","A = P(1 + R/100)ᵀ."],["Half-yearly me R aur T?","R/2 aur T×2."],["Do saath kaam: A=a din, B=b din?","ab/(a+b)."],["Man-days ka niyam?","M₁D₁ = M₂D₂."],["2 saal CI − SI?","P(R/100)²."],["Pipe aur leak me leak ko kya sign?","Minus (−)."],["Efficiency kaise nikalte hain?","Kaam ÷ Din."]],
"M5":[["km/h → m/s?","× 5/18."],["m/s → km/h?","× 18/5."],["Ulti disha relative speed?","Jodo (a + b)."],["Same disha relative speed?","Ghatao (a − b)."],["Downstream speed?","Boat + dhara."],["Upstream speed?","Boat − dhara."],["Platform paar karne me dooori?","Train + platform ki lambai."],["Barabar dooori ki average speed?","2ab/(a+b)."]],
"M6":[["a² − b²?","(a+b)(a−b)."],["Triangle ke angles ka sum?","180°."],["Pythagoras?","a² + b² = c²."],["Polygon ke exterior angles ka sum?","360°."],["Diagonals ka formula?","n(n−3)/2."],["x + 1/x = k to x² + 1/x²?","k² − 2."],["Complementary angles ka sum?","90°."],["Supplementary angles ka sum?","180°."]],
"M7":[["Triangle ka area?","½ × base × height."],["Circle ka perimeter?","2πr."],["Cylinder ka volume?","πr²h."],["Sphere ka surface area?","4πr²."],["Cone ka volume?","⅓πr²h."],["sin 90° = ?","1."],["cos 0° = ?","1."],["Cube ki diagonal?","a√3."]],
"M8":[["nCr = ?","n!/[r!(n−r)!]."],["nPr = ?","n!/(n−r)!."],["Probability ki range?","0 se 1."],["Median kya hai?","Sorted data ka beech ka value."],["Mode kya hai?","Sabse zyada baar aane wala value."],["Pie chart ka poora angle?","360°."],["P(E) + P(not E) = ?","1."],["Do sikke, ek head ek tail ki probability?","1/2."]],
"R1":[["Series me pehle kya dekhein?","Difference (antar)."],["Opposite letter ka position sum?","27."],["Analogy ka pehla step?","Pehle jode ka rishta pakadna."],["Fibonacci series kya hai?","Pichle do numbers ka sum."],["Odd one out me kya dhoondhte hain?","Jo baaki se alag category/type ka ho."],["Perfect squares: 1, 4, 9, 16, ?","25."],["Perfect cubes: 1, 8, 27, ?","64."],["Z ke baad ulti series ka 2 step peeche?","X."]],
"R2":[["Right se position?","27 − left se position."],["Kul students (rank)?","Upar + Neeche − 1."],["Do letters ke beech letters?","Antar − 1."],["Alphabet me vowels kitne?","5 (A, E, I, O, U)."],["A=1 to M=?","13."],["Z ka position?","26."],["Shift coding me +1 ka matlab?","Agla letter."],["Beech wale ke log (A aur B ke beech)?","B ki position − A ki position − 1."]],
"R3":[["Mama ke bachche kya?","Cousin."],["Right turn kitne degree?","90° clockwise."],["Suraj kis disha me nikalta?","Poorv (East)."],["Bhai ki patni?","Bhabhi (sister-in-law)."],["Saala kise kehte hain?","Patni ke bhai ko."],["Parchhai shaam ko kis taraf?","Poorv (East)."],["North-East kin do dishaon ke beech?","North aur East."],["Nana kaun?","Mata ke pita."]],
"R4":[["All + All?","All."],["Some ka ulta?","Some (conversion hota hai)."],["No ka ulta?","No."],["All ka ulta?","Some (All nahi)."],["Conclusion kis par based hota hai?","Sirf diye gaye statements par."],["Assumption kya hai?","Pehle se maani gayi baat jo statement ko sahi banati hai."],["Venn me 'All A are B'?","A ka circle B ke andar."],["'No A is B' ka Venn?","Do alag circles."]],
"R5":[["Clock angle formula?","|30H − 5.5M|."],["Leap year me din?","366."],["Din ginne me 7 ka kya role?","Din ÷ 7 ka remainder = odd days."],["Dice me opposite faces ka sum?","7."],["Mirror image kis taraf ulta?","Left-right."],["Water image?","Upar-neeche ulta."],["Minute ka kaanta ek min me kitne degree?","6°."],["Ghante ka kaanta ek ghante me kitne degree?","30°."]]
});
